blueprint:
  name: Anunciar via Alexa
  description: Anuncia nas caixas Echo selecionadas
  domain: script
mode: queued
fields:
  mensagem:
    selector:
      text: null
    name: Mensagem
    description: O que anunciar?
    required: true
  tipo_mensagem:
    selector:
      select:
        options:
          - label: TTS
            value: tts
          - label: Anúncio
            value: announce
    default: announce
    name: Tipo de mensagem
    description: Escolha o tipo de mensagem (TTS, simplesmente fala, ou Anúncio, emite um alerta antes de falar)
    required: true
  volume:
    selector:
      number:
        min: 0.1
        max: 1
        step: 0.1
    default: 0.8
    name: Volume
    description: Escolha o volume do anúncio (padrão 80%)
  onde_anunciar:
    selector:
      entity:
        filter:
          - integration: alexa_media
            domain: media_player
        multiple: true
    default: []
    name: Onde Anunciar
    description: Escolha as Alexas
    required: true
sequence:
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: "{{ volume }}"
    target:
      entity_id: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 1
      milliseconds: 0
  - service: notify.alexa_media
    data:
      message: "{{ mensagem }}"
      data:
#        type: announce
        type: "{{ tipo_mensagem }}"
      target: "{{ onde_anunciar }}"
  - delay:
      hours: 0
      minutes: 0
      seconds: 10
      milliseconds: 0
  - service: media_player.volume_set
    metadata: {}
    data:
      volume_level: 0.5
    target:
      entity_id: "{{ onde_anunciar }}"
icon: mdi:bullhorn
